version: '{build}'
image: Visual Studio 2022
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - main
skip_tags: true
skip_branch_with_pr: true
max_jobs: 1

configuration: Release

init:
- cmd: >-
    tzutil /s "Russian Standard Time"

    git config --global core.autocrlf input
install:
- ps: >-
    $CommitDateTime = [datetime]::Parse($env:APPVEYOR_REPO_COMMIT_TIMESTAMP)

    $env:BuildDate = $CommitDateTime.ToString('yyyy-MM-dd')

    Update-AppveyorBuild -Version "$env:BuildDate.$env:APPVEYOR_BUILD_NUMBER"
build_script:
- cmd: build.cmd
artifacts:
- path: 'Feeds*.zip'
  name: zip1
- path: 'Fin*.zip'
  name: zip2
deploy:
- provider: GitHub
  tag: $(BuildDate)
  release: $(BuildDate)
  description: 'AppVeyor build #$(APPVEYOR_BUILD_NUMBER): $(APPVEYOR_REPO_COMMIT_MESSAGE)'
  auth_token:
    secure: Oyf/ccEamPwfWLPEZQlf9hPfhGGXu3Kqnmt9saeaTMH2OE6OR0tAt2JkDl/FRR9o
  artifact: zip1,zip2
  force_update: true
  on:
    branch:
      - master
      - main
only_commits:
  files:
    - '*.cs'
    - '*.yml'
skip_commits:
  files:
    - docs\*
    - '**\*.md'
